### PR TITLE
Bitcode libraries

### PR DESCRIPTION
**Pull request by mrigger**
This change implements the linking of bitcode libraries. mx compiles C files in `mx.sulong/libs` to bitcode and passes them with the `sulong.DynamicBitcodeLibraries` option to the Sulong runtime. The Sulong runtime parses the libraries and registers the functions, so that the main program can use them.

### CODE REVIEW

**Comment by chrisseaton** [comment]
We'll also need to do some changes for my idea for allowing libraries to be listed within `.su` files. At the moment I think the list of loaded libraries is totally static.

**Comment by mrigger** [comment]
Yes, the fix for the function registry from this PR should also help to implement that. 

I did not want to have the checkstyle and pylint fix in the history, so I edit the history and pushed a new PR: #161.

**Comment by chrisseaton** [comment]
You don't need to delete a PR to change the history. Just make whatever local changes and then `push --force` and it will replace those already there.

**Comment by mrigger** [comment]
Good to know, thanks!

**Pull request closed without merging**
