### PR TITLE
Add TruffleObject eq/ne specializations to LLVMAddressCompareNode.

### PR DESCRIPTION
**Pull request by mickjordan**

### CODE REVIEW

**Comment by mickjordan** [comment]
The error seems to be related to some download problem from linz. I don't see a way to retry the build without committing another change

**Comment by chrisseaton** [comment]
I've restarted the build.

**Comment by mrigger** [comment]
I updated the download link of Eclipse: #305.

**Comment by mrigger** [comment]
Could you squash the commits before integration? In order to pass the git message gate check you have to rewrite the history anyway.

**Comment by mickjordan** [comment]
On 6/19/16 2:37 AM, Manuel Rigger wrote:
>
> Could you squash the commits before integration? In order to pass the 
> git message gate check you have to rewrite the history anyway.
>
If you can tell me how to do that I will. I amended the commit with the 
bad message (why so anal by the way?)

Mick

**Comment by mrigger** [comment]
This change was integrated with #308.

**Pull request closed without merging**
