### PR TITLE
Remove the GCC and LLVM BC test suites and replace them by launching …

### PR DESCRIPTION
**Pull request by mrigger**
…the LL test suites with -Dsulong.TestBinaryParser=true

The GCC and LLVM .bc test suites were introduced with #444 and #449, since the bitcode parser could not parse and execute
all of the .ll GCC and LLVM test cases. Since the bitcode parser can execute all of the test cases that the textual .ll parser
can execute, the separation of the test suites and suite configuration is no longer necessary, and removed with this change.

### CODE REVIEW

**Comment by mrigger** [comment]
@jkreindl @pointhi @SwapnilGaikwad Could one of you please have a look at this change?

**Comment by jkreindl** [comment]
The changes look good, but if we want to change this anyways maybe we should think about the selection of testsuites. LLVM should be covered by Sulong, which has similar coverage to GCC but is a bit smaller. Compile also seems interesting, just to see that the parser does not crash for invalid code. I think it would be best to run the Sulong and Compile testsuites in travis4 instead of LLVM and GCC.

**Comment by mrigger** [comment]
The PR does not change the test suites that are executed, it only removes existing redundancies. Maybe we can change which test suites are executed as part of another PR?

**Comment by jkreindl** [comment]
Sure, I'll get to that when I have time.

**Comment by SwapnilGaikwad** [comment]
Changes look good to meet too! I agree with @jkreindl .

**Pull request merged**
