### PR TITLE
Add truffle_read_string intrinsic to turn a char* into a String

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by chrisseaton** [comment]
Used for example like this https://github.com/jruby/jruby/compare/truffle-c-exts?expand=1#diff-c14b15a0d092eb68d1ea3908676615e5R188. Otherwise nobody knows to turn the address into something that Ruby can see is a string.

**Comment by mrigger** [comment]
Can we have a test case for this, so we do not accidentally break the new function?

**Comment by chrisseaton** [comment]
Added a test.

**Comment by grimmerm** [comment]
I approve the change.

**Pull request merged**
