### PR TITLE
Support atexit taking function descriptors as well as function handles.

### PR DESCRIPTION
**Pull request by mikehearn**
Correct the atexit return type and add some documentation.

Note, I have signed and sent off the OCA today. I will hopefully appear on the list in a day or two. I figured I could as well get code review started early.

### CODE REVIEW

**Comment by rschatz** [comment]
> Note, I have signed and sent off the OCA today. I will hopefully appear on the list in a day or two. I figured I could as well get code review started early.

No problem, we just need it done before we merge.

**Comment by mikehearn** [comment]
My OCA signature has been processed:

http://www.oracle.com/technetwork/community/oca-486395.html#h

**Comment by grimmerm** [comment]
Good news! 
Can you pls fix that PR and then I'll integrate it.

**Comment by mikehearn** [comment]
Cool. By "fix" you mean the CI failure? I thought that was OCA related, but I guess not. Will rebase and take a look when I get time.

**Comment by rschatz** [comment]
We no longer intrinsify `atexit`. It is now implemented in `libsulong.bc`.
This should now work with all kinds of function pointers naturally, since this is now just regular C code that stores a list of fuction pointers.

If this is still an issue for your use-case, please open a new issue and we can investigate.

**Pull request closed without merging**
