### PR TITLE
Define a potential header for interop functions

### PR DESCRIPTION
**Pull request by chrisseaton**
Starting to sketch out what a header file for using interop functions from C could look like. Just enough to start a conversation by showing how Ruby C extensions could compile against it.

### CODE REVIEW

**Comment by chrisseaton** [comment]
Truffle C used to have versions of most of these method with specific return types. We might well need that but I want to keep this simple to start with, just so I can start to sketch out what Ruby needs.

**Comment by chrisseaton** [comment]
See https://github.com/jruby/jruby/pull/3803. Together with this PR, this is a starting point for whoever is going to work on Sulong interop. Lots of open questions here!

**Comment by eregon** [comment]
It might be interesting to have a type like "ForeignObject"/"TruffleObject", then Sulong can know whatever it does with that is via Interop, and all functions Ruby would expose would either have simple types or that (i.e. VALUE would become ForeignObject for most cases). TruffleObject is already used for similar purposes at the Java level I think.

**Pull request merged**
